# Generated by Django 3.1.6 on 2021-02-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('fname', models.CharField(default='', max_length=50)),
                ('lname', models.CharField(default='', max_length=50)),
                ('profilepic', models.ImageField(upload_to='')),
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('phonenum', models.CharField(default='', max_length=50)),
                ('roomnum', models.CharField(default='', max_length=50)),
                ('subjects', models.CharField(default='', max_length=300)),
            ],
        ),
    ]
